### ISSUE TITLE
Ringarna saknas i Safari

### ISSUE THREAD

**Issue by Konrad77** [meridiumlabs/Meridium.ChallengeBoard#1]
Jag har inte samma ringar som Nathalie hade i skärmdumpen i e-posten.
<img width="1552" alt="skarmavbild 2015-09-17 kl 07 57 43" src="https://cloud.githubusercontent.com/assets/4384932/9926055/3f0a9a48-5d12-11e5-8843-86f486a8e4e7.png">

**Comment by ThaliaA** [comment]
Fixat?
