### ISSUE TITLE
Yoga borde ge samma antal poäng som 'Lyft din egen kroppsvikt i bänkpress'

### ISSUE THREAD

**Issue by kimgunnarsson** [meridiumlabs/Meridium.ChallengeBoard#12]
Pga att du arbetar tuffare med din kropp (hela din kroppsvikt) under ett yogapass än att ligga raklång i en bänk och gör typ en rep...

**Comment by ThaliaA** [comment]
Avhjälpt? ;) Tack för bra synpunkt!
