### ISSUE TITLE
Fel antal poäng på min bräda

### ISSUE THREAD

**Issue by PernillaA** [meridiumlabs/Meridium.ChallengeBoard#13]
Jag får för många poäng på min bräda. Jag har bara gjort stryketräning en gång, men det står två, båda räknas med i min totala poäng. Jag har andra kort som också visar antal ggr men jag har inte gjort dem. De gröna pilarna har jag gjort, de röda har jag inte gjort

![snap1137](https://cloud.githubusercontent.com/assets/5877295/9985602/374fbbc4-602f-11e5-8c91-55870360ea3a.png)

**Comment by ThaliaA** [comment]
Avhjälpt? :)

**Comment by PernillaA** [comment]
Japp :)
