### ISSUE TITLE
Kan inte autentisera mig/registrera poäng

### ISSUE THREAD

**Issue by victor--** [meridiumlabs/Meridium.ChallengeBoard#4]
Jag lyckas inte inte märka utmaningar som avklarade i Firefox 42 Developer Edition i OSX.

Önskat beteende: en utmaning blir avklarad och poäng registeras.

Upplevt beteende: får serverfel.

### Reproduceringssteg:

- Registera en användare (i mitt fall http://challenge.meridium.se/victor)
- Fyll i ett lösenord och kryssa i "Visa publikt"
- Väl inloggad på din profil (http://challenge.meridium.se/victor), klicka på valfri utmaning (i mitt fall klickade jag på "Gå till eller från jobbet") *(bild 1)*
- En omdirigering görs till ~/Authentication **(observera att name är "undefined" i query'n)** *(bild 2)*
- Fyll i lösenordet
- Ett felmeddelande visas och poängen blir inte registerad *(bild 3)*

*Fotnot: även om jag ändrar URL:en från http://challenge.meridium.se/Authentication?name=undefined till http://challenge.meridium.se/Authentication?name=victor så får jag ett serverfel*

*Mitt lösenord blev sparat av webbläsaren när jag skapade kontot, så jag tvivlar på att jag matar in fel uppgifter*

#### Bild 1:
<img width="1656" alt="ch error 1" src="https://cloud.githubusercontent.com/assets/8023473/9927608/6d85ae18-5d20-11e5-910e-b47d0a9502d3.png">
#### Bild 2:
<img width="1680" alt="ch error 2" src="https://cloud.githubusercontent.com/assets/8023473/9927611/737fdf6e-5d20-11e5-9b14-5d3422fef133.png">
#### Bild 3:
<img width="1138" alt="ch error 3" src="https://cloud.githubusercontent.com/assets/8023473/9927612/757ae1c4-5d20-11e5-92a4-0a233d9b4972.png">

**Comment by ThaliaA** [comment]
Går det bättre nu?

**Comment by victor--** [comment]
Nu fungerar det. Tack! :+1:
